### ISSUE TITLE
You forgot a comma before Bionic.

### ISSUE THREAD

**Issue by bnjdg** [vincentbernat/haproxy-debian-repository-wizard#10]
haproxy.debian.net doesn't render well due to the forgotten comma after artful and before bionic.

Line 15 Column 33.

Please fix and be careful next time.

`      Ubuntu: {
        trusty: 'Trusty (14.04 LTS)',
        xenial: 'Xenial (16.04 LTS)',
        artful: 'Artful (17.10)',
        bionic: 'Bionic (18.04 LTS)'
      }
`

**Comment by vincentbernat** [comment]
Thanks! Fixed.
