### ISSUE TITLE
Error installing haproxy 2.0

### ISSUE THREAD

**Issue by RedWolf3121** [vincentbernat/haproxy-debian-repository-wizard#12]
I try to install haproxy with your ppa, and i get this error.
![Captura](https://user-images.githubusercontent.com/34524302/81335976-be4f6080-90a8-11ea-8c6b-904d4f4052da.PNG)

**Comment by vincentbernat** [comment]
You seem to have already installed haproxy in the past using an alternative method. There is a `haproxy` user remaining you should delete. You can use `deluser haproxy`.

**Comment by RedWolf3121** [comment]
Thanks for your help, problem solved.
