### ISSUE TITLE
Incorrect apt source url for Debian 11, containing bpo instead of backports

### ISSUE THREAD

**Issue by bhank** [vincentbernat/haproxy-debian-repository-wizard#16]
https://haproxy.debian.net/#?distribution=Debian&release=bullseye&version=2.4 tells me to add the source `deb http://deb.debian.org/debian bullseye-bpo main` -- but when I run `apt update` it fails with:

```
E: The repository 'https://deb.debian.org/debian bullseye-bpo Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

It looks like it should be `bullseye-backports` instead of `bullseye-bpo`; making that change gets it working for me.

**Comment by vincentbernat** [comment]
Thanks! Fixed.
