### ISSUE TITLE
apt install haproxy=2.6.\*   -  Forbidden

### ISSUE THREAD

**Issue by MarianBojescu** [vincentbernat/haproxy-debian-repository-wizard#17]
In the last few days I have been trying to install haproxy on a Debian 10/11 using this repository

apt install haproxy=2.5.\*
....
Err:1 http://haproxy.debian.net buster-backports-2.5/main amd64 haproxy amd64 2.5.7-1~bpo10+1
  403  Forbidden [IP: 2001:19f0:........ 80]
E: Failed to fetch http://haproxy.debian.net/pool/main/h/haproxy/haproxy_2.5.7-1~bpo10+1_amd64.deb  403  Forbidden [IP: 2001:19f0:........ 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I tried from several sources, but without success

**Comment by vincentbernat** [comment]
Thanks for the notice. I made a mistake with the latest update. This should be fixed now.

**Comment by MarianBojescu** [comment]
Thank you very much
