### ISSUE TITLE
HTTP3/QUIC support

### ISSUE THREAD

**Issue by AnTheMaker** [vincentbernat/haproxy-debian-repository-wizard#19]
Hi there!
I used this repo to install Haproxy 2.7 and everything worked fine, however, I couldn't enable http3 (QUIC) in my haproxy configuration, because it said that the installed haproxy wasn't compiled with QUIC support.
(I followed these steps to enable http3: https://www.haproxy.com/blog/announcing-haproxy-2-6#http3-over-quic)
Is QUIC support planned or do I need to look into a different way of installing haproxy?
Thanks for your help!

**Comment by vincentbernat** [comment]
Nothing is planned yet as no SSL stack has support for it in Debian/Ubuntu.

**Comment by AnTheMaker** [comment]
Okay, thanks for the clarification!

Other question: I saw that HAProxy 2.8 got released, is there an ETA when it'll be available via this repo?
Thanks for your work!

**Comment by AnTheMaker** [comment]
Just saw that 2.8 has been added now, thanks a lot!
