### ISSUE TITLE
Apt key is expired

### ISSUE THREAD

**Issue by shooterbaba** [vincentbernat/haproxy-debian-repository-wizard#2]
Hi,

I am having package authentication error in Debian-Wheezy while following the url  :- http://haproxy.debian.net/

W: GPG error: http://haproxy.debian.net wheezy-backports-1.6 Release: The following signatures were invalid: KEYEXPIRED 1402932313 KEYEXPIRED 1402932313 KEYEXPIRED 1402932313

Please fix this if possible.

Thanks & Regards,

**Comment by vincentbernat** [comment]
Oh, right, on Wheezy, the keyring is too old... Let me fix that.

**Comment by silviogesell** [comment]
Hi,

http://haproxy.debian.net jessie-backports-1.6 InRelease
KEYEXPIRED 1497788068

Please fix this too if possible.
Thanks a lot & Regards

**Comment by vincentbernat** [comment]
I have just tried and the key is not expired. You need to redo the apt-key command to update your local copy.
