### ISSUE TITLE
bookworm-backports-3.0 fails to download

### ISSUE THREAD

**Issue by mildis** [vincentbernat/haproxy-debian-repository-wizard#20]
After digging, it looks like the architecture is not suffixed to the `Contents-<arch>.gz` file nor `main/binary-<arch>` folder.
Updating bookworm to haproxy-3.0 thus fails with message : 
```
W: Skipping acquire of configured file 'main/binary-amd64/Packages' as repository 'http://haproxy.debian.net bookworm-backports-3.0 InRelease' does not s
eem to provide it (sources.list entry misspelt?)
```

**Comment by vincentbernat** [comment]
Thanks. I don't know why it happened. It's fixed.
