### ISSUE TITLE
Upgrade to HAProxy-1.8 on Debian 9 uses wrong pkg name

### ISSUE THREAD

**Issue by hulvei3** [vincentbernat/haproxy-debian-repository-wizard#9]
During an upgrade of HAP on a newly upgrade debian 9 system, I failed to run the final apt-get install cmd successfully after following the instructions.

`apt-get install haproxy/stretch-hdn -t stretch-backports` didn't work for me and resulted in `E: Release 'stretch-hdn' for 'haproxy' was not found`

After looking at [this](https://www.linuxtechi.com/install-configure-haproxy-debian-9-ubuntu-16-04/) I tried just running `apt-get install haproxy -t stretch-backports\*`

This worked.

Not sure if it's my end that were inconsistent?

**Comment by vincentbernat** [comment]
Thanks for the notice! I have fixed this in e1855047000f. Use of `stretch-backports\*` was removed because it could install a too recent version (for example, if you want HAProxy 1.6).
